# Server settings  
server:  
  port: 8081
  
spring:  
  #profiles : dev  
  datasource:  
    type: com.alibaba.druid.pool.DruidDataSource  
    url: jdbc:mysql://127.0.0.1:3306/antifraud_slave?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root  
    password: root  
    driver-class-name: com.mysql.jdbc.Driver
    
mybatis:   
  typeAliasesPackage: cn.unisk.antifraud.domain

# LOGGING  
logging:
    path: 
#    file: ${catalina.home}/logs/antifraud-service.log
    level:
      root: info
      cn.unisk.antifraud.mapper: debug 
      com.ibatis: info 

application:
  message: Hello, Andy 